version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: user           # 自定义用户名
      POSTGRES_PASSWORD: 123456  # 设置你的密码
      POSTGRES_DB: craftcard        # 创建默认数据库
    ports:
      - "5432:5432"                   # 映射端口，允许外部访问
    volumes:
      - pgdata:/var/lib/postgresql/data  # 数据卷，持久化存储数据
    restart: unless-stopped           # 重启策略

volumes:
  pgdata:                             # 定义数据卷
